name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to workflows
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          --request POST \
          --data '{ "event_type": "deploy" }' https://api.github.com/repos/jakelazaroff/todayilearned/dispatches
